#!/usr/bin/python3

# Run this script daily from the networks in front of enp1s0.

import json
import platform
import subprocess
import datetime
import os

data = {
	"Nmap": [],
	"Hostname": "",
	"Scanname": "",
	"Interfacename": "",
	"Date": "",
	"Key": "efc47d5cff7ebd855d6a635025499bdc5a4d14f3eb5c49d4bba6e90b56c51062"
}

def runp(command):
	result = subprocess.run(
		command,
		capture_output=True,
		text=True,
		check=True
	)
	lines = result.stdout.strip().split("\n")
	return lines


def scan(scanip):
	global data

	ipv = "4"
	if ":" in scanip:
		return			## tja
		ipv = "6"
		scanip = scanip + "%"+iface

	data["Nmap"] = runp(["/usr/bin/nmap", "-Pn",  "-"+ipv, scanip ])
	data["Hostname"] = platform.node()
	data["Scanname"] = "mongo12.lewi.nl"
	data["Interfacename"] = "enp1s0"
	data["IPv"] = ipv
	now = datetime.datetime.now()
	data["Date"] = now.strftime("%Y-%m-%d %H:%M:%S")

	f = open("/var/tmp/nchecknetraw-nmap.json", "w")
	f.write(json.dumps(data))
	f.close()

	runp(["curl","-k","--data-binary","@/var/tmp/nchecknetraw-nmap.json","-X","POST","https://nchecknet.lewi.nl/api_nmap"])
	os.remove("/var/tmp/nchecknetraw-nmap.json")

def main():
	scanips = ["192.168.100.12"]
	for s in scanips:
		scan(s)

main()

